# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "PinHead"
include-after = [
	"cmake/cpm.cmake",
	"cmake/IntelPIN.cmake"
]

# Intel PIN
[template.pintool]
type = "custom"
add-function = "add_pintool"
pass-sources = true

# PINHEAD instrumentation
[target.example]
type = "pintool"
sources = [
	"src/*.cpp"
]